name: offline_billing
description: "A new Flutter project."

publish_to:
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^1.0.0
  flutter_rounded_date_picker: ^3.0.2

  #image
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  image_cropper: ^9.1.0

  # database:
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.3

  #invoice
  printing: ^5.14.2
  pdf: ^3.11.3
  intl: ^0.18.1
  share_plus: ^11.0.0
  open_file: ^3.5.10

  #theme
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  flutter_colorpicker: ^1.1.0


  cupertino_icons: ^1.0.8

dev_dependencies:

  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  get: ^4.7.2


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/Poppins/Poppins-Regular.ttf
#    - images/a_dot_ham.jpeg


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf

#        - asset: assets/fonts/WaterBrush-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
